### ISSUE TITLE
Controller Login CORS error

### ISSUE THREAD

**Issue by srodriguezOPT** [open-ness/edgecontroller#21]
Hi,

I've installed a controller+node network-edge setup following the https://github.com/open-ness/specs/blob/master/doc/getting-started/network-edge/controller-edge-node-setup.md guide.

As I need to access the portal from outside, I exposed the kubernetes eaa service (eaa-exposed):
```
NAME               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
eaa                ClusterIP   None           <none>        80/TCP,443/TCP               19h
eaa-exposed        NodePort    10.110.14.48   <none>        80:30228/TCP,443:30146/TCP   6h19m
edgedns            ClusterIP   None           <none>        53/UDP,4204/TCP              19h
interfaceservice   ClusterIP   None           <none>        42101/TCP                    19h
nfd-master         NodePort    10.100.121.8   <none>        8080:32416/TCP               19h
syslog-master      ClusterIP   None           <none>        6514/UDP                     19h
```

pointing the REACT_APP_CUPS_API to http://controller-host-ip:30228 (".env" file), but after executing the make ui-up when i tried to login http://controller-host-ip:3000/login, a CORS error is returned:
![imagen](https://user-images.githubusercontent.com/15909508/75858172-ec3dcd80-5df7-11ea-8792-8dcd5c6b6f7d.png)

How can I access the portal from outside? Is there any other method than the eaa service manual exposition?

Thx

**Comment by amr-mokhtar** [comment]
Hi @srodriguezOPT,
It looks like that you are trying to use the Controller UI from OnPrem with the NE deployment of OpenNESS, which it does not support since NE is using Kubernetes.
If you need to use a UI with the NE deployment, then it should be the Kubernetes Dashboard that was added in 19.12.

There is a guide for setting it up in the NE getting started guide: https://github.com/open-ness/specs/blob/master/doc/getting-started/network-edge/controller-edge-node-setup.md#installing-kubernetes-dashboard

**Comment by srodriguezOPT** [comment]
Yes, you're right.

I thought that Controller UI was accessible from both deployments.

Thx
